version: "3.9"

services:
  postgres:
    container_name: "go_todo_db"
    image: postgres:16.3
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME:-"db-test"}
      POSTGRES_USER: ${POSTGRES_USER:-"db-user"}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-"qwerty"}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
          - "${POSTGRES_PORT:-5436}:5432"
    healthcheck:
        test: [ "CMD-SHELL", "pg_isready -U db-user -d db-test" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  db-data: